apiVersion: v1
kind: Secret
metadata:
    name: {{ printf "%s-app-secrets" .Values.global.project }}
    namespace: {{ .Values.global.namespace }}
    labels:
        app.kubernetes.io/component: {{ printf "%s-app-secrets" .Values.global.project }}
{{- include "empayhrms.labels" . | nindent 8 }}
type: Opaque
data:
    GROQ_API_KEY: {{ .Values.secrets.groqApiKey | b64enc | quote }}
    VITE_GROQ_API_KEY: {{ .Values.secrets.viteGroqApiKey | b64enc | quote }}
    SMTP_USER: {{ .Values.secrets.smtpUser | b64enc | quote }}
    SMTP_PASS: {{ .Values.secrets.smtpPass | b64enc | quote }}
    